import AuthHeader from '@/components/un-auth-header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import  "./styles.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <>
      {/* <AuthHeader/> */}
      <div className='auth-form-layout'>        
      {children}
      </div>
      </>
      
  )
}
