import SideBarComp from '@/components/side-bar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopBarComp from '@/components/top-bar'
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";   
import 'primeicons/primeicons.css'; // Import PrimeIcons CSS
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Doc APP',
  description: 'Generated by create next app',
}

export default function AppLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <>
      <SideBarComp></SideBarComp>
      <TopBarComp></TopBarComp>
      <div className='main'>        
      {children}
      </div>
      </>
  )
}
